name: Coverage badge

on:
  push:
    branches:
      - main
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm install
        working-directory: client
      - run: npm install
        working-directory: server
      - run: npm run verify

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
