name: Tests and coverage

on:
  push:
    branches:
      - main
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - uses: ArtiomTr/jest-coverage-report-action@v2
      - name: install dependencies
        id: coverage
        run: npm ci
      - run: npm test
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        with:
          output: report-markdown
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}


